server:
  port: 8062
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/microservice-book?autoReconnect=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update